name: Build and Test
on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  create-env:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: make venv
        run: |
          python3.12 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: install efmcalculator
        run: |
          pip install ./

      - name: test efmcalculator
        run: |
          python -m unittest
